# Generated by Django 5.0.2 on 2024-02-24 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('политика', 'политика'), ('наука', 'наука'), ('спорт', 'Спорт'), ('экономика', 'Экономика'), ('религия', 'Религия'), ('туризм', 'Туризм'), ('технологии', 'Технологии'), ('сша', 'США'), ('россия', 'Россия'), ('общество', 'Общество'), ('европа', 'Европа')], max_length=30, verbose_name='Тег')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='news.new', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
