# Generated by Django 5.0.2 on 2024-02-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[('политика', 'Политика'), ('наука', 'Наука'), ('спорт', 'Спорт'), ('экономика', 'Экономика'), ('религия', 'Религия'), ('туризм', 'Туризм'), ('технологии', 'Технологии'), ('россия', 'Россия'), ('общество', 'Общество'), ('европа', 'Европа')], max_length=30, verbose_name='Тег'),
        ),
    ]
