# Generated by Django 5.0.2 on 2024-02-25 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_new_view_count_alter_tag_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='dislike_count',
            field=models.ManyToManyField(default=0, related_name='new_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Количество дизлайков'),
        ),
        migrations.AddField(
            model_name='new',
            name='like_count',
            field=models.ManyToManyField(default=0, related_name='new_likes', to=settings.AUTH_USER_MODEL, verbose_name='Количество лайков'),
        ),
    ]
